version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8080:80"
    networks:
      - RIA2
    environment:
      - VUE_APP_API_GATEWAY_URL=https://localhost/api/gateway/

networks:
  RIA2:
      name: RIA2